# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - run: jq
      - run: sudo vim /etc/apt/sources.list
      - run: sudo apt-get install jq
      
