# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - run: curl 'https://raw.githubusercontent.com/BorderCloud/selenium-ide-tool-importFile/main/test/testImportFile.side' | jq '.'
      
