# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Execute importFile
        run: |
          chmod +x importFile.sh
          ./importFile.sh test/testImportFile.side -o ./test.side
        
      - name: Run website
        working-directory: ./test
        run: |
          yarn install
          yarn dev:httpd &
        
      - name: Run servers
        working-directory: ./test
        run: docker-compose -f docker-compose.yaml up -d

      - name: Install selenium-side-runner & drivers
        run: |
            sudo npm install -g selenium-side-runner
          
      - name: Test
        run: |
          selenium-side-runner  --server http://localhost:4444/wd/hub -c "browserName=chrome" ./test.side
          selenium-side-runner  --server http://localhost:4444/wd/hub -c "browserName=firefox" ./test.side
